import {Router} from 'express'; import {z} from 'zod'; import {query} from '../db'; import {requireAuth,AuthedRequest} from '../middleware/auth';
const r=Router(); r.use(requireAuth);
const schema=z.object({name:z.string().min(1),mobile:z.string().min(5),email:z.string().email().optional().or(z.literal('')),business_name:z.string().optional(),gst_number:z.string().optional(),customer_type:z.enum(['Retail','Wholesale','Distributor']),address:z.string().optional(),status:z.enum(['Lead','Active','Inactive']).default('Lead'),follow_up_date:z.string().optional(),notes:z.string().optional()});
r.get('/',async(req,res,next)=>{try{const search=String(req.query.search||'').trim(); const page=Math.max(1,Number(req.query.page||1)); const limit=Math.min(50,Math.max(1,Number(req.query.limit||10))); const offset=(page-1)*limit; const s=`%${search}%`; const count=await query<any>('SELECT COUNT(*)::int count FROM customers WHERE name ILIKE $1 OR mobile ILIKE $1 OR COALESCE(business_name,\'\') ILIKE $1',[s]); const data=await query('SELECT * FROM customers WHERE name ILIKE $1 OR mobile ILIKE $1 OR COALESCE(business_name,\'\') ILIKE $1 ORDER BY created_at DESC LIMIT $2 OFFSET $3',[s,limit,offset]); res.json({data:data.rows,page,limit,total:count.rows[0].count});}catch(e){next(e)}});
r.get('/:id',async(req,res,next)=>{try{const c=await query<any>('SELECT * FROM customers WHERE id=$1',[req.params.id]); if(!c.rowCount)return res.status(404).json({message:'Customer not found'}); const f=await query('SELECT * FROM customer_followups WHERE customer_id=$1 ORDER BY created_at DESC',[req.params.id]); res.json({...c.rows[0],followups:f.rows});}catch(e){next(e)}});
r.post('/',async(req,res,next)=>{try{const b=schema.parse(req.body); const q=await query('INSERT INTO customers(name,mobile,email,business_name,gst_number,customer_type,address,status,follow_up_date,notes) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) RETURNING *',[b.name,b.mobile,b.email||null,b.business_name||null,b.gst_number||null,b.customer_type,b.address||null,b.status,b.follow_up_date||null,b.notes||null]);res.status(201).json(q.rows[0]);}catch(e){next(e)}});
r.put('/:id',async(req,res,next)=>{try{const b=schema.partial().parse(req.body); const fields=Object.entries(b); if(!fields.length)return res.status(400).json({message:'No fields to update'}); const set=fields.map(([k],i)=>`${k}=$${i+1}`).join(', '); const vals=fields.map(([,v])=>v); const q=await query(`UPDATE customers SET ${set},updated_at=NOW() WHERE id=$${vals.length+1} RETURNING *`,[...vals,req.params.id]); if(!q.rowCount)return res.status(404).json({message:'Customer not found'});res.json(q.rows[0]);}catch(e){next(e)}});
r.post('/:id/followups',async(req:AuthedRequest,res,next)=>{try{const b=z.object({note:z.string().min(1),follow_up_date:z.string().optional()}).parse(req.body); const q=await query('INSERT INTO customer_followups(customer_id,note,follow_up_date,created_by) VALUES($1,$2,$3,$4) RETURNING *',[req.params.id,b.note,b.follow_up_date||null,req.user!.id]);res.status(201).json(q.rows[0]);}catch(e){next(e)}});
export default r;
